import { NextRequest, NextResponse } from "next/server";
import { createCalDavEvent, deleteCalDavEvent, discoverICloudCalendars, fetchICloudEvents, openICloudCredentials, updateCalDavEvent } from "@/app/lib/icloud-caldav";
import { loadConnection } from "@/app/lib/connection-store";

async function context() { const sealed = (await loadConnection("icloud"))?.encrypted; if (!sealed) throw new Error("NOT_CONNECTED"); const credentials = await openICloudCredentials(sealed); return { credentials, calendars: await discoverICloudCalendars(credentials) }; }
export async function GET(request: NextRequest) { const configured = Boolean(process.env.CALENDAR_CREDENTIAL_SECRET); try { const { credentials, calendars } = await context(); const start = new Date(request.nextUrl.searchParams.get("from") || Date.now() - 31 * 86400000); const end = new Date(request.nextUrl.searchParams.get("to") || Date.now() + 93 * 86400000); const groups = await Promise.all(calendars.map(c => fetchICloudEvents(credentials, c, start, end).catch(() => []))); return NextResponse.json({ connected: true, configured, calendars: calendars.map(({ id, name, color }) => ({ id, name, color })), events: groups.flat() }); } catch (error) { return NextResponse.json({ connected: false, configured, calendars: [], events: [], error: error instanceof Error && error.message === "AUTH_REQUIRED" ? "auth_required" : "reconnect_required" }, { status: 401 }); } }
export async function POST(request: NextRequest) { try { const body = await request.json(); const { credentials, calendars } = await context(); const calendar = calendars.find(c => c.id === body.calendarId); if (!calendar) throw new Error("CALENDAR_NOT_FOUND"); await createCalDavEvent(credentials, calendar, body); return NextResponse.json({ saved: true }); } catch { return NextResponse.json({ error: "save_failed" }, { status: 400 }); } }
export async function PATCH(request: NextRequest) { try { const body = await request.json(); const { credentials } = await context(); await updateCalDavEvent(credentials, body.resourceUrl, { ...body, uid: body.providerEventId }); return NextResponse.json({ saved: true }); } catch { return NextResponse.json({ error: "save_failed" }, { status: 400 }); } }
export async function DELETE(request: NextRequest) { try { const body = await request.json(); const { credentials } = await context(); await deleteCalDavEvent(credentials, body.resourceUrl); return NextResponse.json({ deleted: true }); } catch { return NextResponse.json({ error: "delete_failed" }, { status: 400 }); } }
