import { NextRequest, NextResponse } from "next/server";
import { discoverCompanyCalendars, openCompanyCredentials } from "@/app/lib/company-caldav";
import { createCalDavEvent, deleteCalDavEvent, fetchICloudEvents, updateCalDavEvent } from "@/app/lib/icloud-caldav";
import { loadConnection } from "@/app/lib/connection-store";
import { providerEventFailure, providerWriteFailure } from "@/app/lib/provider-event-failures";

async function context() { const sealed = (await loadConnection("caldav"))?.encrypted; if (!sealed) throw new Error("NOT_CONNECTED"); const credentials = await openCompanyCredentials(sealed); return { credentials, calendars: await discoverCompanyCalendars(credentials) }; }
function isPersonalCalendar(name: string) { return name.replaceAll(" ", "").toLowerCase() === "내일정"; }
function writableCalendarForResource(calendars: Awaited<ReturnType<typeof discoverCompanyCalendars>>, resourceUrl: string) { return calendars.find(calendar => isPersonalCalendar(calendar.name) && new URL(resourceUrl).toString().startsWith(calendar.url.endsWith("/") ? calendar.url : `${calendar.url}/`)); }
export async function GET(request: NextRequest) { try { const { credentials, calendars } = await context(); const start = new Date(request.nextUrl.searchParams.get("from") || Date.now() - 31 * 86400000); const end = new Date(request.nextUrl.searchParams.get("to") || Date.now() + 93 * 86400000); const groups = await Promise.all(calendars.map(c => fetchICloudEvents(credentials, c, start, end))); return NextResponse.json({ connected: true, calendars: calendars.map(({ id, name, color }) => ({ id, name, color })), events: groups.flat() }); } catch (error) { const failure = providerEventFailure("daou", undefined, error); return NextResponse.json(failure.body, { status: failure.status }); } }
export async function POST(request: NextRequest) { try { const body = await request.json(); const { credentials, calendars } = await context(); const calendar = calendars.find(c => c.id === body.calendarId); if (!calendar || !isPersonalCalendar(calendar.name)) return NextResponse.json({ error: "read_only_calendar" }, { status: 403 }); const event=await createCalDavEvent(credentials, calendar, body); return NextResponse.json({ saved: true, providerEventId:event.uid, resourceUrl:event.resourceUrl }); } catch { return NextResponse.json({ error: "save_failed" }, { status: 400 }); } }
export async function PATCH(request: NextRequest) { try { const body = await request.json(); const { credentials, calendars } = await context(); if (!body.resourceUrl || !writableCalendarForResource(calendars, body.resourceUrl)) return NextResponse.json({ error: "read_only_calendar" }, { status: 403 }); await updateCalDavEvent(credentials, body.resourceUrl, { ...body, uid: body.providerEventId }); return NextResponse.json({ saved: true }); } catch (error) { const failure = providerWriteFailure("daou", error); return NextResponse.json(failure.body, { status: failure.status }); } }
export async function DELETE(request: NextRequest) { try { const body = await request.json(); const { credentials, calendars } = await context(); if (!body.resourceUrl || !writableCalendarForResource(calendars, body.resourceUrl)) return NextResponse.json({ error: "read_only_calendar" }, { status: 403 }); await deleteCalDavEvent(credentials, body.resourceUrl); return NextResponse.json({ deleted: true }); } catch { return NextResponse.json({ error: "delete_failed" }, { status: 400 }); } }
